import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// The LWC runtime, the in-browser compiler worker and the example catalog are
// prebuilt into public/generated by `npm run assets` (see docs/architecture.md),
// so Vite only has to deal with the React shell.
export default defineConfig({
  plugins: [react()],
});
