import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { buildThirdPartyNotices } from './scripts/licenses.ts';

/**
 * Emits dist/THIRD_PARTY_NOTICES.txt covering the app bundle and the prebuilt assets
 * in public/generated, whose packages were recorded by `npm run assets`.
 */
function thirdPartyNotices(): Plugin {
  return {
    name: 'third-party-notices',
    apply: 'build',
    async generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: 'THIRD_PARTY_NOTICES.txt',
        source: await buildThirdPartyNotices(this.getModuleIds()),
      });
    },
  };
}

// The LWC runtime, the in-browser compiler worker and the example catalog are
// prebuilt into public/generated by `npm run assets` (see docs/architecture.md),
// so Vite only has to deal with the React shell.
export default defineConfig({
  plugins: [react(), thirdPartyNotices()],
});
